import type { Language } from './types';

export const LANGUAGES: { id: Language; label: string; native: string }[] = [
  { id: 'en', label: 'English', native: 'English' },
  { id: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { id: 'or', label: 'Odia', native: 'ଓଡ଼ିଆ' },
  { id: 'bn', label: 'Bengali', native: 'বাংলা' },
  { id: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { id: 'mr', label: 'Marathi', native: 'मराठी' }
];

type Key = 'home'|'report'|'alerts'|'training'|'more'|'viewReports'|'incidentFree'|'reportsTitle'|'sitePrompt'|'workingAt'|'continue'|'mySiteReports'|'allSiteReports'|'employeeSearch'|'designation'|'submit'|'installApp'|'appearance'|'nearMiss'|'hazard'|'uc'|'unsafeAct'|'safetyObservation'|'feedback'|'grievance'|'speakUp'|'suggestion'|'changeSite'|'selectSite';

// Core navigation/form strings are translated. All long-form content still needs professional native review before launch.
const messages: Record<Language, Record<Key, string>> = {
  en: { home:'Home', report:'Report', alerts:'Safety Alerts', training:'Training', more:'More', viewReports:'View Reports', incidentFree:'days incident-free', reportsTitle:'Site safety reports', sitePrompt:'Which site are you currently working at?', workingAt:'Your current site', continue:'Continue', mySiteReports:'My Site Reports', allSiteReports:'All Site Reports', employeeSearch:'Search employee ID or name', designation:'Designation', submit:'Submit report', installApp:'Install Safex App', appearance:'Appearance', nearMiss:'Near Miss', hazard:'Hazard', uc:'Unsafe Condition', unsafeAct:'Unsafe Act', safetyObservation:'Safety Observation', feedback:'Feedback', grievance:'Grievance', speakUp:'Speak Up', suggestion:'Suggestion', changeSite:'Change site', selectSite:'Select site' },
  hi: { home:'होम', report:'रिपोर्ट', alerts:'सुरक्षा अलर्ट', training:'ट्रेनिंग', more:'और', viewReports:'रिपोर्ट देखें', incidentFree:'दिन बिना दुर्घटना', reportsTitle:'साइट सुरक्षा रिपोर्ट', sitePrompt:'आप अभी किस साइट पर काम कर रहे हैं?', workingAt:'आपकी वर्तमान साइट', continue:'जारी रखें', mySiteReports:'मेरी साइट की रिपोर्ट', allSiteReports:'सभी साइट की रिपोर्ट', employeeSearch:'कर्मचारी ID या नाम खोजें', designation:'पद', submit:'रिपोर्ट भेजें', installApp:'Safex App इंस्टॉल करें', appearance:'दिखावट', nearMiss:'नियर मिस', hazard:'खतरा', uc:'असुरक्षित स्थिति', unsafeAct:'असुरक्षित कार्य', safetyObservation:'सुरक्षा अवलोकन', feedback:'फीडबैक', grievance:'शिकायत', speakUp:'खुलकर बोलें', suggestion:'सुझाव', changeSite:'साइट बदलें', selectSite:'साइट चुनें' },
  or: { home:'ମୂଳପୃଷ୍ଠା', report:'ରିପୋର୍ଟ', alerts:'ସୁରକ୍ଷା ସତର୍କତା', training:'ପ୍ରଶିକ୍ଷଣ', more:'ଅଧିକ', viewReports:'ରିପୋର୍ଟ ଦେଖନ୍ତୁ', incidentFree:'ଦୁର୍ଘଟଣା ବିନା ଦିନ', reportsTitle:'ସାଇଟ୍ ସୁରକ୍ଷା ରିପୋର୍ଟ', sitePrompt:'ଆପଣ ବର୍ତ୍ତମାନ କେଉଁ ସାଇଟ୍‌ରେ କାମ କରୁଛନ୍ତି?', workingAt:'ଆପଣଙ୍କ ବର୍ତ୍ତମାନର ସାଇଟ୍', continue:'ଆଗକୁ ବଢ଼ନ୍ତୁ', mySiteReports:'ମୋ ସାଇଟ୍ ରିପୋର୍ଟ', allSiteReports:'ସମସ୍ତ ସାଇଟ୍ ରିପୋର୍ଟ', employeeSearch:'କର୍ମଚାରୀ ID କିମ୍ବା ନାମ ଖୋଜନ୍ତୁ', designation:'ପଦବୀ', submit:'ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ', installApp:'Safex App ଇନ୍‌ଷ୍ଟଲ୍ କରନ୍ତୁ', appearance:'ଦେଖାଶୁଣା', nearMiss:'ନିଅର୍ ମିସ୍', hazard:'ବିପଦ', uc:'ଅସୁରକ୍ଷିତ ଅବସ୍ଥା', unsafeAct:'ଅସୁରକ୍ଷିତ କାର୍ଯ୍ୟ', safetyObservation:'ସୁରକ୍ଷା ପର୍ଯ୍ୟବେକ୍ଷଣ', feedback:'ମତାମତ', grievance:'ଅଭିଯୋଗ', speakUp:'କହନ୍ତୁ', suggestion:'ପ୍ରସ୍ତାବ', changeSite:'ସାଇଟ୍ ବଦଳାନ୍ତୁ', selectSite:'ସାଇଟ୍ ବାଛନ୍ତୁ' },
  bn: { home:'হোম', report:'রিপোর্ট', alerts:'নিরাপত্তা সতর্কতা', training:'প্রশিক্ষণ', more:'আরও', viewReports:'রিপোর্ট দেখুন', incidentFree:'দিন দুর্ঘটনামুক্ত', reportsTitle:'সাইট নিরাপত্তা রিপোর্ট', sitePrompt:'আপনি বর্তমানে কোন সাইটে কাজ করছেন?', workingAt:'আপনার বর্তমান সাইট', continue:'চালিয়ে যান', mySiteReports:'আমার সাইটের রিপোর্ট', allSiteReports:'সব সাইটের রিপোর্ট', employeeSearch:'কর্মী আইডি বা নাম খুঁজুন', designation:'পদবি', submit:'রিপোর্ট জমা দিন', installApp:'Safex অ্যাপ ইনস্টল করুন', appearance:'চেহারা', nearMiss:'নিয়ার মিস', hazard:'বিপদ', uc:'অনিরাপদ অবস্থা', unsafeAct:'অনিরাপদ কাজ', safetyObservation:'নিরাপত্তা পর্যবেক্ষণ', feedback:'মতামত', grievance:'অভিযোগ', speakUp:'বলুন', suggestion:'পরামর্শ', changeSite:'সাইট বদলান', selectSite:'সাইট নির্বাচন করুন' },
  pa: { home:'ਮੁੱਖ ਪੰਨਾ', report:'ਰਿਪੋਰਟ', alerts:'ਸੁਰੱਖਿਆ ਅਲਰਟ', training:'ਟ੍ਰੇਨਿੰਗ', more:'ਹੋਰ', viewReports:'ਰਿਪੋਰਟਾਂ ਵੇਖੋ', incidentFree:'ਹਾਦਸੇ ਤੋਂ ਬਿਨਾਂ ਦਿਨ', reportsTitle:'ਸਾਈਟ ਸੁਰੱਖਿਆ ਰਿਪੋਰਟਾਂ', sitePrompt:'ਤੁਸੀਂ ਇਸ ਵੇਲੇ ਕਿਹੜੀ ਸਾਈਟ ’ਤੇ ਕੰਮ ਕਰ ਰਹੇ ਹੋ?', workingAt:'ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਸਾਈਟ', continue:'ਜਾਰੀ ਰੱਖੋ', mySiteReports:'ਮੇਰੀ ਸਾਈਟ ਦੀਆਂ ਰਿਪੋਰਟਾਂ', allSiteReports:'ਸਾਰੀਆਂ ਸਾਈਟਾਂ ਦੀਆਂ ਰਿਪੋਰਟਾਂ', employeeSearch:'ਕਰਮਚਾਰੀ ID ਜਾਂ ਨਾਮ ਖੋਜੋ', designation:'ਅਹੁਦਾ', submit:'ਰਿਪੋਰਟ ਭੇਜੋ', installApp:'Safex ਐਪ ਇੰਸਟਾਲ ਕਰੋ', appearance:'ਦਿੱਖ', nearMiss:'ਨਿਅਰ ਮਿਸ', hazard:'ਖਤਰਾ', uc:'ਅਸੁਰੱਖਿਅਤ ਹਾਲਤ', unsafeAct:'ਅਸੁਰੱਖਿਅਤ ਕੰਮ', safetyObservation:'ਸੁਰੱਖਿਆ ਨਿਰੀਖਣ', feedback:'ਫੀਡਬੈਕ', grievance:'ਸ਼ਿਕਾਇਤ', speakUp:'ਗੱਲ ਕਹੋ', suggestion:'ਸੁਝਾਅ', changeSite:'ਸਾਈਟ ਬਦਲੋ', selectSite:'ਸਾਈਟ ਚੁਣੋ' },
  mr: { home:'मुख्यपृष्ठ', report:'अहवाल', alerts:'सुरक्षा सूचना', training:'प्रशिक्षण', more:'अधिक', viewReports:'अहवाल पहा', incidentFree:'अपघातमुक्त दिवस', reportsTitle:'साइट सुरक्षा अहवाल', sitePrompt:'तुम्ही सध्या कोणत्या साइटवर काम करत आहात?', workingAt:'तुमची सध्याची साइट', continue:'पुढे चला', mySiteReports:'माझ्या साइटचे अहवाल', allSiteReports:'सर्व साइटचे अहवाल', employeeSearch:'कर्मचारी ID किंवा नाव शोधा', designation:'पद', submit:'अहवाल पाठवा', installApp:'Safex App स्थापित करा', appearance:'दिसणे', nearMiss:'नियर मिस', hazard:'धोका', uc:'असुरक्षित स्थिती', unsafeAct:'असुरक्षित कृती', safetyObservation:'सुरक्षा निरीक्षण', feedback:'अभिप्राय', grievance:'तक्रार', speakUp:'बोला', suggestion:'सूचना', changeSite:'साइट बदला', selectSite:'साइट निवडा' }
};

export function t(language: Language, key: Key): string {
  return messages[language][key] ?? messages.en[key];
}
