/**
 * Turn the uploaded SafetyOS design file into modules the app can mount.
 *
 * `SafetyOS — Employee Profile Preview (2).html` is a self-contained page: ~615 lines of
 * CSS, ~600 of markup and ~1260 of vanilla JS driving 18 screens (Case Management,
 * Training Management, Employee Profile, Communications, Document Vault, Audit &
 * Inspection, Form Builder, DM, User & Access, Dashboard, Analytics, Certificates, Export
 * Reports, Direct Data Entry, Daily Management, System Settings), SVG charts, a form
 * builder and CSV / report export.
 *
 * Rewriting that by hand into React would take weeks and would drift from the design the
 * moment either side changed. So the design runs as the design: this script splits it into
 * three generated files and the app mounts them.
 *
 * The only edits made to the author's code are seams, all documented below:
 *   1. every CSS selector is scoped under `.sos` so the design cannot collide with the
 *      worker app's globals.css (both define .app, .page, .sidebar, .modal, --line, --green),
 *   2. the demo employee array becomes `window.__SAFEX_EMPLOYEES__ || []` so the
 *      verified operator session can hand the console the real employee master.
 *
 * Run it after editing the design; never hand-edit the generated files.
 *
 *   npm run design:extract                      # uses the design file in the repo root
 *   node scripts/extract-design.mjs other.html   # explicit input
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DEFAULT_INPUT = resolve(ROOT, 'SafetyOS — Employee Profile Preview (2).html');
const input = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_INPUT;

const src = readFileSync(input, 'utf8');
const OUT_DIR = resolve(ROOT, 'app/components/safetyos/generated');
mkdirSync(OUT_DIR, { recursive: true });

const BANNER =
  '/* GENERATED by scripts/extract-design.mjs from the uploaded SafetyOS design — do not edit by hand. */\n';

/* ------------------------------------------------------------------ 1. CSS */

const styleMatch = /<style>([\s\S]*?)<\/style>/.exec(src);
if (!styleMatch) throw new Error('no <style> block found in the design file');
const css = styleMatch[1];

/**
 * Scope one selector group under `.sos`.
 *
 * `:root`, `html` and `body` collapse onto `.sos` itself so the design's custom properties
 * and base typography stay inside its own subtree instead of leaking into the worker app.
 */
function prefixSelector(selector) {
  return selector
    .split(',')
    .map((raw) => {
      const part = raw.trim().replace(/\s+/g, ' ');
      if (!part) return null;
      if (part === ':root' || part === 'html' || part === 'body') return '.sos';
      if (part === '*') return '.sos *';
      if (/^:root\b/.test(part)) return `.sos${part.slice(5)}`;
      // html.auth-required ... — the host replaces the design's Supabase gate with its own
      // server-verified one, so those states are never applied. Scoping them keeps the rule
      // inert without changing the rest of the sheet.
      if (/^(html|body)\b/.test(part)) return `.sos${part.replace(/^(html|body)/, '')}`;
      return `.sos ${part}`;
    })
    .filter(Boolean)
    .join(',');
}

/** Walk the sheet, recursing into at-rules so nested @media blocks are scoped too. */
function scopeCss(text) {
  let out = '';
  let i = 0;
  while (i < text.length) {
    const brace = text.indexOf('{', i);
    if (brace === -1) {
      out += text.slice(i);
      break;
    }
    const selector = text.slice(i, brace);
    let depth = 1;
    let j = brace + 1;
    while (j < text.length && depth > 0) {
      if (text[j] === '{') depth += 1;
      else if (text[j] === '}') depth -= 1;
      j += 1;
    }
    const body = text.slice(brace + 1, j - 1);
    const head = selector.trim();
    if (head.startsWith('@media') || head.startsWith('@supports') || head.startsWith('@layer') || head.startsWith('@container')) {
      out += `${selector}{${scopeCss(body)}}`;
    } else if (head.startsWith('@')) {
      out += `${selector}{${body}}`; // @keyframes, @font-face, @page
    } else {
      out += `${prefixSelector(selector)}{${body}}`;
    }
    i = j;
  }
  return out;
}

const scopedCss = scopeCss(css);
writeFileSync(
  resolve(ROOT, 'app/safetyos.css'),
  `/* GENERATED by scripts/extract-design.mjs — do not edit by hand.\n`
  + ` * Source: ${input.slice(ROOT.length + 1)}\n`
  + ` * Every selector is scoped under .sos so the design cannot collide with globals.css.\n`
  + ` * Regenerate with \`npm run design:extract\` after editing the design.\n`
  + ` */\n${scopedCss}\n`
);

/* --------------------------------------------------------------- 2. markup */

/**
 * Markup is everything between <body> and the page's own <script>.
 *
 * Not a <body>…</body> regex: the report-export function builds a whole HTML document
 * inside a template literal, so the first </body> in the file belongs to that string and a
 * lazy match would swallow the entire script.
 */
const bodyStart = src.indexOf('<body>') + '<body>'.length;
const scriptStart = src.indexOf('<script>', bodyStart);
if (bodyStart < 6 || scriptStart === -1) throw new Error('could not locate the body/script boundary');
const markup = src.slice(bodyStart, scriptStart).trim();

writeFileSync(
  resolve(OUT_DIR, 'markup.ts'),
  `${BANNER}export const DESIGN_MARKUP = ${JSON.stringify(markup)};\n`
);

/* --------------------------------------------------------------- 3. script */

const scriptEnd = src.indexOf('</script>', scriptStart);
if (scriptEnd === -1) throw new Error('unterminated <script>');
let script = src.slice(scriptStart + '<script>'.length, scriptEnd);

/**
 * EMPLOYEE SEAM — the one deliberate change to the design's own code.
 *
 * Only the authenticated host may supply employees. The standalone design stays empty.
 */
const anchor = 'const employeeDirectory=';
const seamStart = script.indexOf(anchor);
if (seamStart === -1) throw new Error('EMPLOYEE SEAM: could not find `const employeeDirectory=`');
const arrayEnd = script.indexOf('];', seamStart);
if (arrayEnd === -1) throw new Error('EMPLOYEE SEAM: could not find the end of the demo employee array');

script =
  script.slice(0, seamStart)
  + `      const employeeDirectory=(typeof window!=='undefined'&&Array.isArray(window.__SAFEX_EMPLOYEES__))?window.__SAFEX_EMPLOYEES__:[];`
  + script.slice(arrayEnd + 1); // drop the `;` that closed the original declaration

writeFileSync(
  resolve(OUT_DIR, 'script.ts'),
  `${BANNER}export const DESIGN_SCRIPT = ${JSON.stringify(script)};\n`
);

console.log('design :', input.slice(ROOT.length + 1));
console.log('css    :', scopedCss.length, 'bytes -> app/safetyos.css');
console.log('markup :', markup.length, 'bytes -> app/components/safetyos/generated/markup.ts');
console.log('script :', script.length, 'bytes -> app/components/safetyos/generated/script.ts');
